### Machine Learning (ML) - Course Outcomes (COs)

Course Name : Machine learning
Credit : 3

Upon successful completion of this course, B.Tech students will be able to:

1. **CO-1: Data Preprocessing & Pipeline Engineering:** Apply exploratory data analysis, feature engineering, and preprocessing techniques to transform raw datasets into clean structures ready for machine learning pipelines.
2. **CO-2: Supervised Learning Paradigms:** Implement and mathematically analyze linear, non-linear, and ensemble classification/regression algorithms to uncover patterns in labeled historical datasets.
3. **CO-3: Unsupervised Learning Paradigms:** Apply clustering and dimensionality reduction algorithms to uncover hidden structural configurations, compress data, and segment unlabeled datasets.
4. **CO-4: Model Evaluation & Hyperparameter Tuning:** Evaluate model performance using advanced statistical metrics and execute robust cross-validation strategies to mitigate underfitting and overfitting.
5. **CO-5: Deep Learning Foundations:** Construct, train, and troubleshoot deep artificial neural networks, applying optimization algorithms to process non-linear representations.
6. **CO-6: Explainable AI & Metaheuristic Optimization:** Evaluate model interpretability using Explainable AI (XAI) frameworks and apply global optimization techniques to solve complex hyperparameter tuning trade-offs.

---

### Activity to Course Outcome Mapping

| Syllabus Unit & Activity Name | Duration | Step-by-Step Execution Plan | Recommended Tools | Mapped Course Outcome | Grading Rubric & Breakdown |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **1. Data Preprocessing & Exploratory Data Analysis (EDA)**<br>🧼 *The Data Wrangling & Cleaning Hackathon* | **1 Week**<br>(Out-of-class prep + 1 Lab Session) | 1. Provide a massive, dirty dataset filled with missing values, extreme outliers, non-numerical strings, and unscaled columns.<br>2. **Task 1:** Perform advanced EDA using statistical visualizations (correlation heatmaps, boxplots).<br>3. **Task 2:** Handle missing data using strategic imputations (KNN Imputer/Iterative Imputer).<br>4. **Task 3:** Address multi-collinearity, manage categorical imbalances using SMOTE, and scale numerical vectors. | Python (Pandas, Seaborn, Scikit-learn), Jupyter Notebook | **CO-1** | **Total: 10 Marks**<br>• Integrity of exploratory data analysis (3M)<br>• Quality of Imputation & Feature Engineering (3M)<br>• Automation Pipeline Efficiency (2M)<br>• Pipeline Reproducibility (2M) |
| **2. Supervised Learning Models**<br>🏆 *The Classifier Battleground* | **1 Lab Session**<br>(2–3 Hours) | 1. Assign teams a real-world classification challenge (e.g., *Credit Card Fraud Detection or Hate Speech Classification*).<br>2. Teams must train three diverse algorithms: a baseline Linear/Logistic Model, a Tree-Based Method (Decision Trees/Random Forests), and a Distance-Based Method (SVM or KNN).<br>3. **Task:** Generate a comprehensive classification report highlighting the distinct behavioral trade-offs of each model under the same constraints. | Python, Scikit-Learn | **CO-2** | **Total: 10 Marks**<br>• Correct implementation of all 3 algorithms (3M)<br>• Handling of class imbalance during model training (3M)<br>• Comparative Analysis Report quality (4M) |
| **3. Unsupervised Learning & Dimensionality Reduction**<br>🔍 *The High-Dimensional Compression Lab* | **1 Lab Session**<br>(2 Hours) | 1. Provide an image dataset or high-dimensional transactional profile database.<br>2. **Task 1:** Apply Principal Component Analysis (PCA) to project the data down into a lower-dimensional space while retaining $\ge 90\%$ variance.<br>3. **Task 2:** Run K-Means and Hierarchical Clustering algorithms on the compressed dataset.<br>4. **Task 3:** Find the optimal cluster configuration using Elbow and Silhouette analysis methodologies. | Python (Scikit-Learn, Matplotlib) | **CO-3** | **Total: 10 Marks**<br>• Mathematical validation of PCA variance target (3M)<br>• Accurate Clustering implementation (3M)<br>• Validation metrics analysis (Silhouette/Elbow plots) (4M) |
| **4. Model Evaluation & Hyperparameter Selection**<br>🧪 *The Overfitting Diagnosis & Tuning Lab* | **1 Lab Session**<br>(2 Hours) | 1. Deliver an intentionally overfitted baseline model that displays stellar training accuracy but suffers a massive performance drop on test splits.<br>2. **Task 1:** Plot learning curves to diagnose the variance/bias trade-off profile.<br>3. **Task 2:** Implement stratified $k$-fold cross-validation.<br>4. **Task 3:** Execute Grid Search and Randomized Search algorithms to discover the absolute optimal parameter space that resolves the overfitting issue. | Python, Scikit-Learn | **CO-4** | **Total: 10 Marks**<br>• Accurate Diagnosis of Learning Curves (2M)<br>• Proper Cross-Validation setup (3M)<br>• Hyperparameter search execution and performance improvement (5M) |
| **5. Deep Learning Foundations**<br>🧠 *The Neural Network Construction Clinic* | **1 Lab Session**<br>(2 Hours) | 1. Students transition from simple machine learning architectures to multi-layer deep neural networks.<br>2. **Task 1:** Build a multi-layer feedforward network from scratch or using an framework.<br>3. **Task 2:** Experiment with different structural activation functions (ReLU, Sigmoid), optimization algorithms (SGD, Adam), and regularization elements (Dropout, $L_2$ regularization).<br>4. **Task 3:** Track loss convergence over multiple epochs to isolate vanishing/exploding gradient behaviors. | TensorFlow, Keras, or PyTorch | **CO-5** | **Total: 10 Marks**<br>• Architecture configuration and network synthesis (4M)<br>• Convergence monitoring and loss curve profiling (3M)<br>• Strategic usage of Regularization/Optimization steps (3M) |
| **6. Explainable AI & Global Optimization**<br>⚙️ *The Black-Box Model Decoupling & Metaheuristic Tuning Lab* | **2 Weeks**<br>(Mini-Project / Take-home assignment) | 1. Provide a complex "black-box" model (like a deep ensemble framework) that yields high predictive metrics but low intrinsic transparency.<br>2. **Task 1:** Apply Explainable AI (XAI) frameworks like SHAP or LIME, or decode the model's inner mechanics using an interpretable surrogate model (e.g., a Decision Tree).<br>3. **Task 2:** Implement a Metaheuristic algorithm (such as Particle Swarm Optimization or Ant Colony Optimization) to autonomously discover optimal model parameters, bypassing standard grid searching.<br>4. **Task 3:** Compile a research report highlighting the optimization path and feature importance correlations. | SHAP/LIME Libraries, Custom Python Metaheuristic Scripts | **CO-6** | **Total: 20 Marks**<br>• Successful extraction of feature importance via XAI/Surrogate Models (6M)<br>• Design and convergence tracking of the Metaheuristic optimizer (6M)<br>• Structural interpretation of optimization parameters (4M)<br>• Report architecture and data synthesis (4M) |
